// For user Features
import addtocart from "./addtocart.png"
import alert from "./alert.png"
import browser from "./browser.png"
import calculator from "./calculator.png"
import cashback from "./cashback.png"
import compare from "./compare.png"
import coupon from "./coupon.png"
import daily from "./daily.png"
import deal from "./deal.png"
import email from "./email.png"
import excusive from "./exclusive.png"
import expired from "./expired.png"
import feature from "./feature.png"
import language from "./language.png"
import location from "./location.png"
import offer from "./offer.png"
import optimization from "./optimization.png"
import personalization from "./personalized.png"
import printer from "./printer.png"
import profile from "./profile.png"
import reviews from "./reviews.png"
import search from "./search.png"
import share from "./share.png"
import socialmedia from "./socialmedia.png"
import store from "./store.png"
import update from "./update.png"
import vote from "./vote.png"
import vaucher from "./voucher.png"

// For admin features 
import addvertise from '../Admin/addvertise.png'
import affiliat from '../Admin/affiliate.png'
import analytics from '../Admin/analytics.png'
import approved from '../Admin/approved.png'
import calender from '../Admin/calendar.png'
import cashless from '../Admin/cashless.png'
import category from '../Admin/category.png'
import communication from '../Admin/communication.png'
import creater from '../Admin/creater.png'
import feedback from '../Admin/feedback.png'
import help from '../Admin/help.png'
import lifestyle from '../Admin/lifestyle.png'
import management from '../Admin/management.png'
import newsletter from '../Admin/newsletter.png'
import performance from '../Admin/performance.png'
import restore from '../Admin/restore.png'
import secure from '../Admin/secure.png'
import seo from '../Admin/seo.png'
import ui from '../Admin/ui.png'

export {/*For user features*/addtocart,alert,browser,calculator,cashback,compare,coupon,daily,deal,email,excusive,expired,feature,language,location,offer,optimization,personalization,printer,profile,reviews,search,share,socialmedia,store,update,vote,vaucher, /* For Admin features */ addvertise,affiliat,analytics,approved,calender,cashless,category,communication,creater,feedback,help,lifestyle,management,newsletter,performance,restore,secure,seo,ui}
